### ISSUE TITLE
Question about making filenames same as folder

### ISSUE THREAD

**Issue by somacruz10** [Morilli/bnk-extract#3]
Your tool is great! But I have a question, is there a possibility to give file in folders their name? This need for when you extract files in different languages, finding simillar sound files can be a problem.

**Comment by Morilli** [comment]
How exactly would this look like? Each folder can contain numerous files, so in order to match them you probably need to compare them one-by-one anyways (and compare same folders).

**Comment by somacruz10** [comment]
I cannot compare files 1 by 1 if I don't know second language and if there more than 1 file in folder.

Something like this: 
![image](https://user-images.githubusercontent.com/9373905/211701452-0a1222e8-7908-4e2a-9a54-e019ca6d863e.png)

It will have folder name and number value. I have some tool that does it, but it requires to extract files using Ravioli Game Tools first, it takes long time. But in the end all files in folder have same name and order number in all language. "Attack 3" in English will be same quote as "Attack 3" in Spanish.

But extracting by your tool is faster and better. I even made a simple python script that takes files out of folders and assigns folder names to them. But files from different language has different order, because they sorted in folder by their names which is their ID. And each language has different ID for same files so you can't sort them as you need.

I guess their's ID order in .bnk or .bin file is same in all languages, so if you assign each folder's name to each file while putting them in folder and add a number (to prevent file conflicts) they will be always have same Order in all languages.
If I could I would edit tool myself, but I don't know C and how to read .bnk and .bin files. So if you have a possibility to edit your tool this will helps a lot, I begging you pls.

**Comment by Morilli** [comment]
Implemented in 4080dcc4c7c921860fa58832b3f6af72c6dce725.
